sudo: false
language: php

php:
  - 7.0

branches:
  only:
    - master

notifications:
  email: false

before_script:
  - composer install

script:
  - php index.php

env:
  - APP_ENV=test SLACK_HOOK=#gonorthsites_testing

after_script:
- echo "Test!"
